// In Javascript we use 'try...catch' statement to anticipate and handle errors

try {
  throw Error("This is an error")
} catch (e) {
  console.log(e)
}
